/*
 * Copyright (C) 2024-2026 Focus by Rj
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.focusbyrj.app.util

import android.content.Context
import java.util.Collections
import java.util.Random

object SummaryQuotes {

    val MORNING_QUOTES = listOf(
        // Batch 1: Chaos & Caffeinated Delusion + Snarky Productivity
        "Good morning! The simulation is running, and your rendering is almost complete.",
        "Today’s forecast: 90% chance of winging it, 10% pure luck.",
        "Wake up and choose violence—or at least choose to answer emails aggressively fast.",
        "You're only one cup of coffee away from feeling completely overwhelmed, but faster.",
        "Look at the bright side: in about 14 hours, you get to lie down again.",
        "Let's go pretend to care about corporate buzzwords for a living wage.",
        "Your bed is setting you up for failure with all that comfort. Break up with it.",
        "Don't let the alarm clock win. It's just a tiny computer that yells at you.",
        "Rise up! The universe demanded your presence, unfortunately.",
        "Put on your armor of caffeine and mild disinterest.",
        "Let's turn this 'oh no' into a 'hell yeah' (or at least a 'meh, fine').",
        "Good morning! May your meetings be canceled and your Wi-Fi never drop.",
        "Today, you will achieve greatness. Or at least clear your browser history.",
        "Wake up! The local economy needs your questionable spending habits.",
        "Time to go show this day who's boss (hint: it's whoever invented espresso).",
        "Your to-do list has been waiting all night to judge your life choices.",
        "Let's knock out these tasks before the existential dread realizes we're awake.",
        "Rise and shine! The circus is in town, and you’re running the main tent.",
        "Channel your inner chaos demon and conquer this task list.",
        "Today’s strategy: Nod solemnly, take notes, do whatever you want anyway.",
        "Get up. Those luxury snacks aren't going to buy themselves.",
        "You’ve got this! And if you don't, just blame it on a software glitch.",
        "Morning routine: 10% hygiene, 90% contemplating alternate career paths.",
        "Let's get through today so we can complain about it over pizza.",
        "You are capable of doing hard things. Like getting out of bed right now.",
        "Time to unleash your weaponized competence.",
        "Good morning! Go be the reason someone else has to update their checklist.",
        "If you can't be good today, at least be efficient.",
        "May your motivation last longer than your morning commute.",
        "Load up the tasks! It’s time to trade sanity for gold.",
        "Let’s get this over with so we can go back to horizontal living.",
        "You're a rockstar. Well, maybe an indie band on a budget, but still.",
        "Morning rule: Speak softly, carry a large mug of dark roast.",
        "Go make your future self proud (or at least slightly less stressed).",
        "The to-do list is locked and loaded. Time to pull the trigger.",
        "Act confident. Nobody else knows what they're doing either.",
        "Start the day strong, or at least start it on time.",
        "Today: Less thinking, more doing, zero drama.",
        "Today's goal: Look busy enough that nobody asks you to take the minutes.",
        "Put your game face on; your pillow will wait for you.",
        "Let’s conquer this list before lunchtime ruins our focus.",
        "Your tasks called. They miss you. Don't leave them hanging.",
        "Today is full of endless possibilities, mostly involving paperwork.",
        "May your brain boot up without any fatal error screens.",
        "Good morning! Remember: 'Per my last email' is the polite way to say 'Can you read?'",
        "Time to turn that anxiety into actionable deliverables.",
        "Let's crush this queue before someone invents a new emergency.",
        "Your daily reminder that ignoring a task does not make it disappear.",
        "Do the hardest thing first, so the rest of the day feels like coasting downhill.",
        "Look at you, ready to tackle items you've postponed for three weeks.",
        "Coffee in hand, eyes half open, unstoppable.",
        "Let's handle these chores so you can spend your evening guilt-free.",
        "Today's priority: Don't let tiny annoyances hijack your whole day.",
        "You survived yesterday. Today’s tasks are basically child’s play.",
        "Time to pretend to be an organized, structured professional.",
        "Get it done, check it off, move on with your life.",
        "Today’s mission: Outsmart your own procrastination.",
        "Good morning! The inbox is full, but your patience is fuller.",
        "Don't stare at the mountain. Just clear the first rock.",
        "Efficiency is just laziness with a plan. Let's be very efficient today.",
        "Time to knock these out so we can scroll on our phones without remorse.",
        "Your potential is unlimited; your daily battery, however, is not. Spend it well.",
        "Wake up! The world is waiting for your specific brand of genius.",
        "Let's get through the checklist before your willpower evaporates.",
        "Today: High velocity, low friction.",
        "You are smarter than your to-do list. Prove it.",
        "Good morning! Go out there and collect some metaphorical dubs.",
        "Be faster than the requests coming into your inbox.",
        "It’s showtime. Let's make it look effortless.",
        "Today's agenda: Strike first, strike fast, take an early lunch.",
        "Every checked box is a tiny victory over chaos.",
        "Grab the steering wheel; today is not driving itself.",
        "Wake up and handle business so business stops handling you.",
        "Time to execute the plan, even if the plan was made 5 minutes ago.",
        "Let’s make today’s accomplishments undeniable.",

        // Batch 2: Morning Briefings
        "Wake up! The world isn’t going to confuse itself.",
        "Today’s mood: Heavily caffeinated with a mild chance of productivity.",
        "Time to go make decisions you can defend with a straight face later.",
        "Wake up, buttercup. The queue is calling and it has no mercy.",
        "Let’s knock these out before someone schedules an emergency sync about syncing.",
        "Your task list is ready. Don’t make eye contact, just attack.",
        "Good morning! Go be the hero your inbox definitely doesn't deserve.",
        "You can sleep when you're rich, or at least when it’s 9 PM tonight.",
        "Let’s convert today’s dread into today’s 'done' list.",
        "Time to unleash that aggressive typing energy.",
        "Good morning! The simulation is running and your daily quests are active.",
        "Get up. Your rivals are already drinking overpriced lattes and scheming.",
        "Today’s priority: Handle the critical stuff, delegate the rest to the void.",
        "Drink the coffee, ignore the existential dread, crush the checklist.",
        "Wake up! You’ve got spreadsheets to intimidate and deadlines to bully.",
        "Let’s make today so efficient it feels like a cheat code.",
        "Good morning! May your notifications stay calm and polite today.",
        "Time to show up and pretend we’ve got everything entirely under control.",
        "One task at a time, zero unnecessary drama.",
        "Good morning! Let’s clear the board early so afternoon-you can slack off.",
        "Wake up and take names. Or just check boxes, whichever is easier.",
        "Today’s forecast: High speed, low drag, maximum caffeine.",
        "Let’s turn that morning momentum into an early evening escape.",
        "Good morning! Strike while the motivation is actually in the room.",
        "Clear the queue, win the day, secure the bragging rights.",
        "Time to put in the reps and cross off the mess.",
        "Good morning! Let’s turn vague intentions into finished tickets.",
        "Wake up. The clock is running and the list isn't shrinking itself.",
        "Today’s agenda: Focus, finish, refuse additional work, repeat.",
        "Let’s make short work of this checklist before lunch distracts us.",
        "Good morning! Don’t overthink it, just start clicking.",
        "Time to get down to business before your brain realizes what’s happening.",
        "Wake up! Energy follows action, so start moving some pixels.",
        "Today is a fresh canvas. Try not to spill your beverage on it.",
        "Tackle the worst task first and coast the rest of the day like a legend.",
        "Let’s turn today into a masterclass in aggressive efficiency.",
        "Wake up, execute the plan, enjoy the evening guilt-free.",
        "Good morning! Show the to-do list who’s actually running things.",
        "Today’s target: Zero open items by sunset.",
        "Get in, get it done, get out. No lingering allowed.",
        "Good morning! Make today count before it counts you out.",
        "Time to turn raw potential into cold, hard checkmarks.",
        "Wake up! Let’s get these tasks out of your head and into the archive.",
        "Good morning! Let’s synergize some deliverables or whatever the buzzwords are.",
        "Another morning of turning bean water into professional-sounding messages.",
        "Wake up! There are meetings that could have been emails waiting for you.",
        "Today’s plan: Look extremely focused while doing only what matters.",
        "Good morning! Remember: Staring intensely at your screen looks like hard work.",
        "Time to face the daily barrage of 'as per my previous message'.",
        "Wake up! The economy needs your begrudging participation today.",

        // Batch 3: Morning Briefings
        "Cue the training montage where you miraculously fix your life in under three minutes.",
        "The coffee is pitch black, the calendar is merciless, and someone has to settle the score.",
        "Biological scan complete: meatbag host requires immediate chemical stimulation to function.",
        "Discipline isn't a feeling; it’s an operational protocol. Execute task one.",
        "Let’s commit some metaphorical arson through aggressively competent project management.",
        "Quest objective loaded: Clear the backlog before your character runs out of mana.",
        "Maximum effort today—or at least medium effort with great hair.",
        "Statistically, staring at a problem while sighing has a 0% resolution rate.",
        "Nobody is coming to do the heavy lifting for you; grab the bar.",
        "In three billion years the sun will swallow the Earth, but today you still have to finish this spreadsheet.",
        "Are you really going to let a bunch of digital pixels intimidate you?",
        "Silence the inner critic by moving too fast for it to catch up.",
        "Warning: Unchecked ambitions without execution will result in severe afternoon regret.",
        "Break the first bottleneck and watch the rest of the dominoes fall.",
        "Fourth wall status: broken. Productivity status: still pending your cooperation.",
        "A cup of spite, two teaspoons of ambition, and zero excuses.",
        "Treat your attention like currency—stop spending it on cheap distractions.",
        "Incoming transmissions indicate a high probability of uninvited busywork. Defend your perimeter.",
        "Confidence doesn't come from certainty; it comes from surviving the friction.",
        "If you move fast enough, the imposter syndrome won't be able to find you.",
        "Pick the task that makes your stomach drop. Obliterate that one first.",
        "Captain's log: Morale is questionable, but the mission parameters remain non-negotiable.",
        "Look at this checklist: it’s practically begging for mercy.",
        "Entropy never sleeps; why should your aspirations?",
        "Rule number one: Stop negotiating with yourself after you've already made the plan.",
        "Another thrilling episode of 'How I Outsmarted Modern Bureaucracy' begins right now.",
        "Cut the theatrical sighs and just click the button.",
        "Pressure turns carbon into diamonds, or dust—your choice entirely.",
        "Pro tip from your friendly neighborhood UI: Procrastinating now makes you a hostage later.",
        "Every masterpiece was built by someone who wanted to stay in bed but didn't.",
        "Tactical priority: Eliminate the noise before it claims your morning.",
        "You're only trapped by the tasks you refuse to look in the eye.",
        "Bring maximum swagger to minimum-interest tasks.",
        "Your competitors are counting on you hitting snooze. Disappoint them.",
        "Treat this queue like bowling pins and throw a strike.",
        "What would a ridiculously capable version of you do right now? Do that.",
        "Don't pray for an easy day; build thicker skin.",
        "Look alive, superhero. The world is full of bad ideas and you're the countermeasure.",
        "Efficiency isn't about rushing; it's about not doing things you'll have to redo.",
        "The algorithm expects you to scroll; shock it by producing instead.",
        "Brute force will solve whatever finesse cannot.",
        "A single decisive action carries more weight than ten hours of overthinking.",
        "Activate tunnel vision: world off, objective locked.",
        "I’d tell you to be careful out there, but where’s the fun in that? Go wreck the queue.",
        "Small daily disciplines quietly compound into undeniable dominance.",
        "Speed is a weapon. Deploy it early.",
        "Can we just agree to crush these deliverables before anyone initiates an unnecessary conference call?",
        "Honor the commitments you made when you were feeling inspired.",
        "Show the calendar that you're the one holding the pen.",
        "Soundtrack rolling, timer running—let's make something happen.",

        // Batch 4: Morning Briefings
        "Cue the orchestral swell while you dramatically contemplate opening that terrifying first document.",
        "Fate whispered to the warrior, but today, let’s see if the warrior even bothered organizing their inbox.",
        "Neural pathways synchronized; processing today's incoming chaos at maximum throughput.",
        "Gravity is currently holding you to this rotating rock—might as well get something done before physics changes its mind.",
        "Breach the fortress of delayed decisions and clear the rooms one by one.",
        "Somewhere out there, an amateur is aggressively succeeding purely out of spite. Match their frequency.",
        "Friction creates heat, and heat burns away hesitation. Strike early.",
        "Look, fourth-wall break: knocking out these top three tasks is purely for your own ego, so make it look cool.",
        "Zero debates with the clock today. Move on instinct.",
        "Sub-routine initiated: Converting human reluctance into cold, measurable kinetic output.",
        "Channel the unearned confidence of an executive presenting an unverified bar chart.",
        "The standard you walk past today is the standard you accept for the rest of the quarter.",
        "Throw some metaphorical glitter on this disaster and tackle the ugliest part first.",
        "Identify the single lynchpin task that makes three other problems instantly evaporate.",
        "Somewhere between existential dread and raw ambition lies the exact sweet spot where real work gets done.",
        "Your competitors didn’t take yesterday off, but they might hesitate this morning—exploit the gap.",
        "Incoming transmission: High likelihood of pointless busywork attempting to hijack your focus. Deploy countermeasures.",
        "A blunt instrument beats a brilliant idea that stays stuck in drafts.",
        "Consider this your official license to ignore low-priority background noise until the real fire is out.",
        "Act like you’re being paid by the completed objective.",
        "Precision over panic; velocity over perfection.",
        "You’ve survived worse odds with less information. Lock in.",
        "Rip off the band-aid, delete the hesitation, and pull the lever.",
        "Stop waiting for the stars to align when you can just move the telescope.",
        "Every empire was built by someone who had plenty of reasons to delay and ignored all of them.",
        "Load the primary weapon system: intense focus and absolute disregard for trivial interruptions.",
        "Nobody wrote a history book about the person who almost sent an important proposal.",
        "The difference between an obstacle and a stepping stone is purely how hard you hit it.",
        "Cut the excuses down to zero and let the momentum do the heavy lifting.",
        "Why tiptoe through today when you can leave footprints everywhere?",
        "A well-executed checklist is indistinguishable from sorcery to disorganized people.",
        "Treat today like a high-speed heist: get in, grab the results, get out clean.",
        "Hesitation is just fear in a cheap business suit. Push past it.",
        "Direct your attention like a blowtorch—cut through the thickest steel on the board first.",
        "You are not here to maintain the status quo; you're here to clear the board.",
        "Warning: Waiting for perfect inspiration will result in guaranteed failure. Start messy.",
        "Bring maximum swagger to minimum-interest obligations.",
        "Discipline is simply refusing to let your temporary mood sabotage your permanent ambitions.",
        "Turn the ambient static of daily life into pure drive.",
        "If the path ahead is muddy, put on heavier boots and keep marching.",
        "Treat distraction like a hostile entity trying to drain your life bar.",
        "A single completed task provides more clarity than forty minutes of strategy meditation.",
        "Operate at a tempo that leaves no room for self-doubt.",
        "Let's treat this morning like an action movie opening sequence: fast, loud, and brutally efficient.",
        "The mountain doesn't care about your mood; it only cares about your steps.",
        "Shed the dead weight of last week's dropped balls and start fresh.",
        "Build the momentum snowball until nothing in the queue can stand in front of it.",
        "Make your future self look back at today and say, 'Damn, they actually pulled that off.'",
        "Strip the problem down to its bare metal and fix the core.",
        "Lights, camera, ruthless execution.",

        // Batch 5: Morning Briefings
        "Synchronize internal chronometers: we're breaching the morning backlog in three, two, one.",
        "Friction is merely the universe's way of confirming you are actually moving forward.",
        "Roll the dramatic cold open where the protagonist contemplates escaping through the bathroom window.",
        "The laws of physics demand these tickets be closed by a conscious entity. Regrettably, that’s you.",
        "Vaporize the easiest obstacle on the board first to generate instant kinetic momentum.",
        "Corporate folklore says if you finish tasks fast enough, they just give you more. Let's test that theory.",
        "A master craftsman never curses their tools; sharpen your focus and cut clean through the list.",
        "Optimism is overrated; let's rely on spite and sheer stubbornness today.",
        "Neural core defragmented. All tactical operational systems green for immediate deployment.",
        "Suppress the ambient panic and secure the perimeter around your primary deliverable.",
        "Dear scriptwriters: give me a plot twist today where everything just works on the first attempt.",
        "Two kinds of people exist: those who dread the queue, and those who treat it like target practice.",
        "The soundtrack just kicked into double-time. Move like you have somewhere legendary to be.",
        "Excuses consume the exact same amount of breath as results. Pick one.",
        "Chimichangas and daydreaming can wait; turning down the chaos meter cannot.",
        "Empty the bucket of yesterday's dropped balls before trying to carry today's water.",
        "Smile warmly at the camera so the algorithm doesn't detect your mild existential crisis.",
        "Main quest loaded. Side quests are strictly disabled until the boss task is defeated.",
        "Identify the single task creating the most mental drag. Delete its existence from the board.",
        "Every legendary journey begins with a single step, followed by checking if lunch is ready yet.",
        "Channel the unyielding energy of an overly confident rogue AI running on overclocked hardware.",
        "You didn't survive 100% of your worst days just to get bullied by a calendar invite.",
        "Target acquired. Lock on, strip away the background chatter, and fire.",
        "Look at this mess: an absolute buffet of opportunities to prove everyone wrong.",
        "Execute protocol Alpha: pretend you know what you're doing until results happen.",
        "The difference between panic and poise is having a numbered list. Look down; you have one.",
        "Brute force is underrated when applied with surgical precision.",
        "If you're going to make a mistake today, make it with breathtaking confidence.",
        "Cut the theatrical sighs. The faster we start, the faster we can resume ignoring society.",
        "Stand in the arena. Take the hits, check the boxes, walk away with the loot.",
        "Biological telemetry: Caffeine levels rising, tolerance for inefficiency dropping.",
        "Treat today's schedule like a heist movie: get in, grab the assets, leave zero trace.",
        "Doubt is a luxury item you simply cannot afford at current market rates.",
        "Direct your attention like an industrial laser through the thickest problem on your plate.",
        "Cue the slow zoom on the hero's determined face. It's go-time.",
        "The universe rewards motion, not flawless theoretical contemplation.",
        "Bypass the drama, counter the distractions, and ship the payload.",
        "A tiny crack in your resolve will flood the engine room. Keep the bulkheads sealed.",
        "Warning: Looking at social media now will reduce your intelligence stats by 40%.",
        "Tackle the ugly tasks while the world is still rubbing sleep out of its eyes.",
        "Make today so undeniably productive that your imposter syndrome resigns in disgrace.",
        "Engage overdrive. We have deadlines to terrorize.",
        "Nobody ever conquered an empire while lying sideways negotiating with an alarm.",
        "The queue is a puzzle. Solve the corner pieces first.",
        "Bring your absolute sharpest blades to this butter-knife fight.",
        "Decide right now whether you're driving the narrative or just riding in the trunk.",
        "Action produces information; sitting still produces only speculation.",
        "Break the fourth wall, wink at the invisible audience, and dismantle that spreadsheet.",
        "Strip the emotion out of the task. It's just input and output.",
        "Ignition sequence complete. Clear the launchpad."
    )

    val EVENING_QUOTES = listOf(
        // Batch 1: Couch Rot & Decompression + Sarcastic Mic Drops & System Resets
        "Shift over! You survived another 8 hours of adulting without crying in public.",
        "Shut the laptop lid like you're slamming a door on a bad salesman.",
        "Brain status: Offline. Please do not reboot until sunrise.",
        "You are officially released from custody. Go home.",
        "Whatever didn't get finished today wasn't meant for this timeline.",
        "Congratulations! You have completed today's tutorial on modern survival.",
        "Time to put the brain in low-power mode and consume carbs.",
        "Your couch has been holding down the fort all day. Go relieve it of duty.",
        "Turn off your monitor. The pixels are getting tired.",
        "Logging out! Any incoming pings will be treated as spam.",
        "You did the things! Now go stare into the middle distance for an hour.",
        "Evening protocol: Sweatpants engaged, responsibilities declined.",
        "Take off the professional mask; it’s time to be a weird goblin again.",
        "You survived today's barrage of minor inconveniences.",
        "Rest is productive. Go produce some high-quality naps.",
        "Put down the phone, close the apps, let your brain defragment.",
        "Today’s work is done. Time to turn on the TV and scroll on your phone anyway.",
        "You gave 100% today (or at least an acceptable percentage). Good job.",
        "Stop thinking about work. The company isn't paying for your evening brain cycles.",
        "Wrap yourself in a blanket like a burrito of pure achievement.",
        "You made it across the finish line. Go collect your reward: snacks.",
        "The sun is down, and so is your willingness to tolerate nonsense.",
        "Unclench your jaw, drop your shoulders, exhale the corporate air.",
        "Today’s tasks are toast. Go put your feet up.",
        "Level complete! Save your progress and power down.",
        "You worked hard. Your bed is sending you frantic invites.",
        "Done! If anyone needs you, tell them to send a carrier pigeon (it will be ignored).",
        "Time to swap spreadsheets for streaming services.",
        "You didn't get everything done, but you got enough done. Call it a win.",
        "Evening vibe: Completely unreachable.",
        "Let the day fade into the background. It's snack o'clock.",
        "Close down all your mental browser tabs before the system crashes.",
        "Shift over. You are no longer responsible for the state of the universe.",
        "Go melt into your bed like a stick of butter on warm toast.",
        "You did great. Time to reward yourself with zero cognitive load.",
        "No more tasks allowed in this headspace tonight.",
        "Celebrate: You didn't flip a single desk today!",
        "The day has been defeated. Go enjoy the spoils of victory (sleep).",
        "Logging off before someone asks for 'one quick favor'.",
        "Night mode activated. Goodbye world, hello mattress.",
        "Clocking out. Future-You is going to be so mad at Present-You tomorrow, but who cares?",
        "Task engine terminated. No further commands accepted.",
        "May your sleep be deep and your alarm tomorrow be gentle (or broken).",
        "You made decisions all day. Tonight, the only decision is: which snack first?",
        "Archive today’s data. It’s time for a factory reset.",
        "Done! Go be a totally unproductive, perfectly happy human.",
        "You showed up, you tackled stuff, you conquered. Dismissed!",
        "The day is officially dead. Long live the night.",
        "Turn off the notifications. You are not on call for humanity.",
        "Drop the pencil, walk away, pretend the to-do list doesn't exist.",
        "Another day closer to the weekend. We take those.",
        "Rest well. You’ll need all that energy to pretend to work tomorrow.",
        "End-of-day summary: Nobody died, some things got done, good enough.",
        "You're done! Go do that horizontal thing you love so much.",
        "Save your energy for tomorrow's plot twists.",
        "You fought the good fight today. Now go surrender to your pillow.",
        "Pack it up, pack it in. Let the sweet silence begin.",
        "You’ve spent enough brain juice for one day. Time to recharge.",
        "Put today in the history books and lock the cover.",
        "You crossed the finish line in one piece. Take the trophy and sleep.",
        "No more problem-solving until the sun comes back.",
        "Congratulations on surviving another spin around the sun.",
        "Log off, disconnect, exist purely as a cozy organism.",
        "That’s all folks! Go catch some quality Z's.",
        "Sign-off time. May your dreams contain zero unread emails.",
        "You crushed it today. Go let your brain recover from all that heavy lifting.",
        "Tonight’s schedule: 100% rest, 0% responsibilities.",
        "Clock stopped. Time to put reality on pause.",
        "You're done being useful for today. Go be completely useless and proud.",
        "Put a fork in today, because it is done.",
        "Rest up, warrior. The battlefield resets at 8:00 AM.",
        "You gave it your all. Now give your bed your all.",
        "Work is temporary, but a good night of sleep is legendary.",
        "Checkmate, today. You didn't beat me.",
        "Daily mission cleared. Shutting down system.",

        // Batch 2: Evening Briefings
        "Day complete! Time to enter horizontal hibernation mode.",
        "Shut the laptop. The work day is officially deceased and buried.",
        "Good evening! You survived, which is honestly the main performance metric.",
        "Time to put your brain on airplane mode for the night.",
        "Shift’s over! Go be completely unproductive and refuse to feel bad about it.",
        "Close the tabs, kick off your shoes, and melt directly into the couch.",
        "Good evening! The tasks have officially declared a ceasefire.",
        "You gave today everything you had. Now give your pillows some attention.",
        "Time to switch from 'problem solver' to 'couch potato'.",
        "Day’s done! Go enjoy the sweet, sweet sound of zero alerts.",
        "Good evening! If an activity requires deep thought tonight, decline it.",
        "Log off, power down, and go reclaim your personal life.",
        "Time to trade the desk chair for a much softer surface.",
        "Good evening! You did the heavy lifting, now go collect your downtime.",
        "Put today to bed so you can put yourself to bed shortly after.",
        "Shift over! Any remaining work has officially expired until tomorrow.",
        "Good evening! You have successfully passed today’s endurance test.",
        "Time to disconnect from the internet and connect with comfort food.",
        "The sun is down, which means your availability is at absolute zero.",
        "Good evening! Go do nothing and do it with unmatched excellence.",
        "Time to shut down the brain cells until further notice.",
        "You made it! Now go recharge those completely drained batteries.",
        "Good evening! Let today go; it’s already yesterday in some parts of the world.",
        "Time to relax like you’ve got zero responsibilities on your plate.",
        "Work mode: Disabled. Cozy mode: Fully operational.",
        "Logging off. If anyone needs you, they can practice the art of waiting.",
        "Good evening! You didn’t throw your computer out the window—take the win.",
        "Time to shut down before you send a message you’ll have to apologize for.",
        "Day complete! Go eat something tasty and judge bad television.",
        "Close the laptop lid with unnecessary dramatic flair.",
        "Good evening! The to-do list has been muted and placed in the corner.",
        "Time to swap active spreadsheets for completely mindless entertainment.",
        "You survived today's nonsense. That deserves a gold medal (or a snack).",
        "Good evening! Put the work thoughts in a mental drawer and lock it.",
        "Shift over! You’re officially off the clock and completely unreachable.",
        "Time to go stare into space like an absolute champion.",
        "Good evening! Today is officially done bothering you.",
        "Drop the mouse, back away from the desk, and nobody gets hurt.",
        "You did what you could, now let the rest sort itself out.",
        "Good evening! Let’s pretend tomorrow doesn’t exist for the next eight hours.",
        "Clock out, check out, pass out. The holy trinity of evening routines.",
        "Good evening! Today’s operation is officially stamped 'concluded'.",
        "Time to enjoy the evening quiet before tomorrow’s plot unfolds.",
        "Shut down the screen. Your eyes deserve a break from glowing rectangles.",
        "Good evening! You’ve officially earned your uninterrupted rest.",
        "Time to power down and let the world spin without your input.",
        "Day’s done. Don’t let your brain work unpaid overtime in your head.",
        "Good evening! Go enjoy the horizontal life you were meant to live.",
        "Time to rest up before the next round of daily adventures begins.",
        "Shift ended. Brain empty. Good night.",

        // Batch 3: Evening Briefings
        "Roll the credits on today's mess; nobody needs an encore.",
        "The ledger is closed. What’s done is profit; what’s left belongs to the shadows.",
        "Host battery reserves dropping below safe operational thresholds. Initiate low-power mode.",
        "Leave today’s battles on the field. Don’t drag wounded thoughts into your living room.",
        "Congratulations on not drop-kicking your router into the sun today.",
        "Save file created. You may now safely detach from the simulation.",
        "Maximum chill engaged. If snacks aren't involved, do not knock on this door.",
        "Unclench every muscle you’ve been using to hold the world together since sunrise.",
        "Work has ended; continuing to stress about it is strictly unpaid labor.",
        "The stars don't care about your unfinished checklist, and tonight, neither should you.",
        "Drop the armor. You're off the clock and off the hook.",
        "System notification: Overthinking tonight will not alter tomorrow's code.",
        "Walk away from the desk like an action hero walking away from an explosion.",
        "Rest isn't a trophy for finishing everything; it's the fuel that keeps the engine alive.",
        "Whatever fell through the cracks today can make friends with the dust down there.",
        "Fade to black on the active tasks. The set is cleared.",
        "Your brain has officially clocked out; trying to use it now will void the warranty.",
        "Darkness falls, the screen goes dark, and your sanity returns to baseline.",
        "Surviving modern society for twelve straight hours deserves a Michelin star.",
        "Cut the power to the mental turbine. Coast into the silence.",
        "Plot twist: Tomorrow’s problems can wait while you turn into a sentient couch cushion.",
        "There is zero ROI on losing sleep over things that can only be fixed in daylight.",
        "Seal the vault. Nothing enters, nothing leaves until sunrise.",
        "Fourth-wall reminder: You survived today’s writers' room nonsense. Go eat something.",
        "Peace arrives the moment you realize today was enough, flaws and all.",
        "Pack away the gear. The perimeter is secure for the night.",
        "If your brain starts replaying awkward interactions from years ago, hit the mental mute button.",
        "A quiet evening is the ultimate act of rebellion against the endless grind.",
        "Cease all active cognitive processing. Your memory buffer requires defragmentation.",
        "Let the dust settle where it landed; tonight is for breathing clean air.",
        "Take the win for staying upright, and bury the rest.",
        "Shut the viewport. The universe will keep spinning without your active supervision.",
        "Pajamas are the uniform of victorious champions off-duty.",
        "No further deliverables will be acknowledged by this department until further notice.",
        "You fought well, made some questionable choices, and lived to tell the tale. Perfection.",
        "Silence the internal narrator; it's time for the credits to roll in peace.",
        "Tuck the worries into a mental drawer. The lock holds until morning.",
        "Resting deeply is an aggressive strategy for winning tomorrow.",
        "Step back and let the silence wash off the residual static of the day.",
        "Achievement unlocked: Navigated chaos with minimal casualties.",
        "The invoice for today's effort has been submitted. No overtime authorized.",
        "Turn down the internal volume until only tranquility remains.",
        "Even superheroes have to take off the suit and eat junk food.",
        "Don't judge the entire voyage by the rough waves you crossed this afternoon.",
        "Eject the mental cartridge and blow the dust off your thoughts.",
        "Gravity is pulling you horizontally for a reason; surrender to it.",
        "A closed screen is the best shield against midnight dread.",
        "Allow your mind to drift away from output and settle into stillness.",
        "Another lap around the track survived without a blowout. Park it.",
        "Exit stage left. The theater is empty, the lights are down, and you are free.",

        // Batch 4: Evening Briefings
        "Cue the slow-motion walk away from the fiery wreckage of today's completed calendar.",
        "The sun sinks, the ledger is sealed, and true wisdom lies in refusing to open it again tonight.",
        "Thermal throttling detected in biological CPU; purging temporary cache and cutting auxiliary power.",
        "You occupied physical space, manipulated tools, and didn't break reality. Solid execution.",
        "Any task attempting to enter your mind past sunset is legally trespassing on your peace.",
        "Weapons cold, perimeter locked. No further engagements authorized until daylight.",
        "Exhale the day’s turbulence; the landing gear is down and the runway is clear.",
        "If your brain tries to start an unprompted internal monologue about old mistakes, deploy immediate tranquilizers.",
        "Gravitational pull maximized: descend smoothly into horizontal suspension.",
        "A closed screen is the ultimate armor against late-night existential panic.",
        "You carried the weight across the finish line; drop the barbell.",
        "Victory isn't always pretty; sometimes it’s just surviving twelve hours without losing your temper.",
        "Seal the bulkhead. What’s outside stays outside until 0800.",
        "Let the unfinished items sit in the dark and think about what they’ve done.",
        "Quiet evenings are the secret laboratory where tomorrow's resilience is synthesized.",
        "The day has been judged, categorized, and archived. Dismiss the jury.",
        "Switch your operational mode from 'impact driver' to 'dormant asset'.",
        "Unclench the muscles you forgot you were holding tight since lunchtime.",
        "Surrendering to rest is a tactical redeployment, not a retreat.",
        "Fade out the soundtrack. The credits are rolling and the theater is clearing.",
        "Your worth is not a running tally on a whiteboard. Let it be.",
        "Cut the mental broadcast; static is vastly superior to late-night worry.",
        "Pack the instruments away; the concert ended the moment you stepped away from the desk.",
        "Let tomorrow figure itself out—it hasn't earned your attention yet.",
        "A clean break from effort is what separates professionals from burnt-out amateurs.",
        "Archive today’s data packets and begin system cooling protocols.",
        "Step off the treadmill before your sanity gets chewed up in the belt.",
        "Nothing on that screen is worth trading your REM cycles for.",
        "You threw your best punches at today; now let your hands drop.",
        "Let the silence settle over the room like fresh snow.",
        "Cease active operations. Reclaiming baseline human sanity is now priority one.",
        "Give your nervous system the memo that the battlefield has emptied.",
        "The stars managed to show up without your assistance; trust the universe to run itself tonight.",
        "Put down the mental chisel; the statue isn't getting any better at midnight.",
        "Victory drinks tonight, tactical adjustments tomorrow.",
        "Draw the curtain on today's performance—flaws, triumphs, and everything in between.",
        "Empty the RAM, lock the doors, and refuse all external pings.",
        "Resting like a champion is the only way to avoid fighting like a zombie tomorrow.",
        "No more problem-solving algorithms allowed in this sector tonight.",
        "You stood your ground, pushed the line forward, and held the perimeter. Rest easy.",
        "Release the death grip on today’s outcomes; they belong to history now.",
        "The machine requires oil and downtime. Provide both.",
        "Let the evening absorb the static of the day until only calm remains.",
        "You don't need to justify shutting down; you just need to do it.",
        "Eject the day's stress like spent shell casings.",
        "Step away from the control panel before you accidentally press something expensive.",
        "Peace is not the absence of tasks; it’s the choice to ignore them when off duty.",
        "Allow your consciousness to drift completely off the grid.",
        "Another lap around the track completed without a total engine blowout. Park it.",
        "Stage dark. House lights up. You're free.",

        // Batch 5: Evening Briefings
        "Cut to black. Cue the synth-heavy end credits while the protagonist stares into the middle distance.",
        "Purging temporary memory buffers. Engaging low-power diagnostic mode.",
        "Audience review of today: 6/10 for plot cohesion, 10/10 for pure unhinged survival.",
        "The day was what it was. Add nothing more to it in your mind.",
        "Legally speaking, any thought regarding spreadsheets past this hour is unauthorized labor.",
        "Transform immediately into a boneless, horizontal organism of pure comfort.",
        "Cease fire across all sectors. Fall back to home base and count your remaining sanity.",
        "Rest is not a luxury retreat; it is the fertile soil where tomorrow's clarity grows.",
        "File today under 'Mysteries We Will Never Revisit' and weld the cabinet shut.",
        "Let the world run on autopilot for the next twelve hours; it won't crash without you.",
        "You manipulated physical matter, traded digital tokens, and survived. That's a wrap.",
        "Unload the mental ammunition. The firing range is closed.",
        "If your brain attempts to load an embarrassing memory from seven years ago, force-quit the app.",
        "The scoreboard is locked. Step off the court and hit the showers.",
        "Tonight’s forecast: 0% chance of you caring about tomorrow's problems before dawn.",
        "You held the line against the horde of incoming notifications. Stand down, soldier.",
        "Drop the heavy pack. The march has concluded for this cycle.",
        "Post-credits scene: You, on the couch, consuming snacks with zero narrative consequence.",
        "Silence the internal narrator; their commentary has exceeded its runtime.",
        "A closed screen is the ultimate shield against midnight dread.",
        "Every hero has to take off the spandex suit before they get a rash. Unwind.",
        "The universe operated fine for billions of years without your input; it can handle tonight.",
        "Seal the hatches. No incoming transmissions will be processed until 0800 hours.",
        "Take the messy victory, leave the perfectionism on the cutting room floor.",
        "Eject the mental cartridge and blow the dust off your thoughts.",
        "You pushed the needle as far as it would go today. Let gravity do the rest.",
        "Deactivate combat readiness. Reclaim baseline human serenity.",
        "What didn't get done today simply lacked the clearance to enter your evening.",
        "Dim the house lights. The performance is over and the auditorium is clearing.",
        "Your bed has officially initiated docking maneuvers. Prepare for impact.",
        "Release the death grip on today's outcomes; they belong to the archives now.",
        "Drop the mental chisel; the sculpture is done for the night.",
        "No further deliverables will be acknowledged by this biological unit.",
        "Turn the static down to absolute zero.",
        "Congratulations on successfully avoiding a public breakdown. Take the win.",
        "The invoice for today’s energy has been paid in full. Do not work overtime for free.",
        "Unclench the muscles you've been using to hold reality together since morning.",
        "Save progress, detach peripherals, and allow the system to cool down.",
        "Step away from the control panel before you press something that requires paperwork.",
        "Tomorrow is an unwritten script; tonight is the intermission.",
        "Lay your weapons by the door. Peace is the only objective remaining.",
        "The mental ledger is balanced. Close the book.",
        "Recharging is an act of defiance against burnout. Sleep like a champion.",
        "Exit stage left with whatever dignity remains intact.",
        "No tactical debrief tonight. Just let the mind drift into static.",
        "You gave what you had, survived what you had to, and won the right to rest.",
        "Powering down auxiliary engines. Drifting safely in orbit.",
        "Allow your consciousness to untether from productivity metrics.",
        "Another lap completed without throwing a rod through the engine block. Park it.",
        "Stage dark. Microphone dropped. Good night."
    )

    private const val PREFS_NAME = "summary_quotes_deck"
    private const val KEY_MORNING_DECK = "morning_deck_indices"
    private const val KEY_EVENING_DECK = "evening_deck_indices"

    /**
     * Gets the next truly random, non-repeating morning quote.
     * Uses a full shuffled deck across all 275 quotes so no quote is repeated
     * until every single quote has been shown.
     */
    @Synchronized
    fun getNextMorningQuote(context: Context): String {
        return getNextQuoteFromDeck(
            context = context,
            quotesList = MORNING_QUOTES,
            deckKey = KEY_MORNING_DECK
        )
    }

    /**
     * Gets the next truly random, non-repeating evening quote.
     * Uses a full shuffled deck across all 275 quotes so no quote is repeated
     * until every single quote has been shown.
     */
    @Synchronized
    fun getNextEveningQuote(context: Context): String {
        return getNextQuoteFromDeck(
            context = context,
            quotesList = EVENING_QUOTES,
            deckKey = KEY_EVENING_DECK
        )
    }

    private fun getNextQuoteFromDeck(
        context: Context,
        quotesList: List<String>,
        deckKey: String
    ): String {
        if (quotesList.isEmpty()) return ""
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        val deckString = prefs.getString(deckKey, null)

        val currentIndices: MutableList<Int> = if (deckString.isNullOrEmpty()) {
            createNewShuffledDeck(quotesList.size)
        } else {
            deckString.split(",")
                .mapNotNull { it.trim().toIntOrNull() }
                .filter { it in quotesList.indices }
                .toMutableList()
        }

        if (currentIndices.isEmpty()) {
            currentIndices.addAll(createNewShuffledDeck(quotesList.size))
        }

        val chosenIndex = currentIndices.removeAt(0)

        // Save updated deck
        prefs.edit().putString(deckKey, currentIndices.joinToString(",")).apply()

        return quotesList[chosenIndex]
    }

    private fun createNewShuffledDeck(size: Int): MutableList<Int> {
        val list = (0 until size).toMutableList()
        list.shuffle(Random(System.currentTimeMillis()))
        return list
    }
}
