name: Build & Release APK

on:
  release:
    types: [published]   # Automatically triggers ONCE for any release published on GitHub Web UI (v1.0.10+ supported)
  workflow_dispatch:    # Enables manual trigger button in GitHub Actions

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9'
          validate-wrappers: false
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Decode Keystore File
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > keystore.jks

      - name: Build and Sign Release APK
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/keystore.jks
          STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          gradle assembleRelease --no-daemon

      - name: Upload APK as Workflow Artifact
        uses: actions/upload-artifact@v4
        with:
          name: focus-by-rj-signed-apk
          path: app/build/outputs/apk/release/*.apk
          retention-days: 14

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/*.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}